api_platform:
  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    html: [ 'text/html' ]

  eager_loading:
    max_joins: 50

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  title: 'Api Gestion des demandes'
  version: '1.0.0'