
api_platform:
    title: 'Gestion des Demandes de Terrain'
    description: 'API pour la gestion des demandes de terrain et des utilisateurs.'
    version: '1.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
        pagination_partial: true
        pagination_via_cursor:
            enabled: false
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']
    collection:
        pagination:
            items_per_page_parameter_name: 'itemsPerPage'
