gesdinet_jwt_refresh_token:
  refresh_token_class: Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken
  ttl: 2592000            # 30 jours, en secondes
  firewall: api           # doit correspondre au nom de ton firewall JWT
  token_parameter_name: refresh_token
