knp_snappy:
  pdf:
    enabled:    true
    binary:     '%env(WKHTMLTOPDF_PATH)%'
    options:    
      encoding: 'UTF-8'
      default-header: false
      page-size: A4
      margin-top: 10mm
      margin-right: 10mm
      margin-bottom: 10mm
      margin-left: 10mm
      enable-local-file-access: true